# Q1. Gauss Seidel and Gauss Jacobi

### i. Write a function to check whether a given square matrix is diagonally dominant. 
__Test the function on a randomly generated 4 × 4 matrix.__

In [46]:
import numpy as np

def matrix_generator() -> int :
    return np.random.randint(-10, 10, size=(4, 4))

In [47]:
def isDiagonallyDominant(matrix):
    # Getting the length of the square matrix
    _len = len(matrix)
    
    # Iterating from 0 to length
    for i in range(_len):
        
        # Diagonal element is always in format of:
        # (0,0), (1,1), (2,2), ... (_len-1, _len-1)
        dia = matrix[i][i]
        
        # if the diagonal element, is less than,
        # sum of set of elements in the row except the diagonal element
        if dia < sum(set(matrix[i]) - set([dia])):
            
            # Represents not diagonally dominant
            return False
        
    # Represents diagonally dominant
    return True

In [48]:
mat = matrix_generator()
print(mat)
isDiagonallyDominant(mat)

[[ -1  -4  -8   1]
 [-10  -2  -9   9]
 [  0  -5   9   9]
 [ -7   5  -9  -1]]


True

### ii. Write a function to generate Gauss Seidel Iteration for a given square matrix.  
__The function should also return the values of 1, ∞ and Frobenius
norms of iteration matrix. Generate a random 4 ×4 matrix. Report
the Iteration matrix and its norm values returned by the function along
with the input matrix.__ 

In [49]:
def calculate_norms(matrix):
    out = {}
    
    # INF norm is max of sum of row values
    out['inf-norm'] = max([sum(i) for i in matrix])
    
    # ONE norm is max of sum of column values
    for i in range(len(matrix[0])):
        temp = 0
        for j in range(len(matrix)):
            temp += matrix[j][i]
        cols[i] = temp
    out['1-norm'] = max(cols)
    return out

matrix = matrix_generator()
print(matrix)
calculate_norms(matrix)

[[ 1 -3  9 -1]
 [ 6  4  9 -4]
 [-3  6  9  3]
 [ 6  7 -3  7]]


{'inf-norm': 17, '1-norm': 24}