# Q1. Gauss Seidel and Gauss Jacobi

### i. Write a function to check whether a given square matrix is diagonally dominant. 
__Test the function on a randomly generated 4 × 4 matrix.__

In [33]:
import numpy as np

def matrix_generator() -> int :
    return np.random.randint(-20, 20,size=(4, 4))

In [72]:
def isDiagonallyDominant(matrix):
    # Getting the length of the square matrix
    _len = len(matrix)
    
    # Making values in the matrix absolute
    matrix = np.absolute(matrix)
    
    # Iterating from 0 to length
    for i in range(_len):
        
        # Diagonal element is always in format of:
        # (0,0), (1,1), (2,2), ... (_len-1, _len-1)
        dia = matrix[i][i]
        
        # if the diagonal element, is less than,
        # sum of set of elements in the row except the diagonal element
        if dia < sum(set(matrix[i]) - set([dia])):
            print(sum(set(matrix[i]) - set([dia])) , '----', dia)
            # Represents not diagonally dominant
            return False
        
    # Represents diagonally dominant
    return True

In [73]:
mat = matrix_generator()
print(mat)
isDiagonallyDominant(mat)

[[  3 -10 -19   6]
 [ -4  14  -3   2]
 [  3 -17  15 -11]
 [ 12  14 -16  -2]]
35 ---- 3


False

### ii. Write a function to generate Gauss Seidel Iteration for a given square matrix.  
__The function should also return the values of 1, ∞ and Frobenius
norms of iteration matrix. Generate a random 4 ×4 matrix. Report
the Iteration matrix and its norm values returned by the function along
with the input matrix.__ 

In [76]:
def calculate_norms(matrix):
    out = {'inf-norm': None, '1-norm': None, 'frob-norm': 0}
    cols = []
    
    # INF norm is max of sum of row values
    out['inf-norm'] = max([sum(i) for i in matrix])
    
    # ONE norm is max of sum of column values
    for i in range(len(matrix[0])):
        temp = 0
        for j in range(len(matrix)):
            temp += matrix[j][i]
        cols.append(temp)
        
        for j in range(len(matrix)):
            out['frob-norm'] += matrix[i][j]**2
        
    out['1-norm'] = max(cols)
    out['frob-norm'] = round(np.sqrt(out['frob-norm']),2)
    return out

matrix = matrix_generator()
print(matrix)
calculate_norms(matrix)

[[-19  18   0   0]
 [ 19  -3  -2  17]
 [-10 -12   8   4]
 [ 19 -17  -4  14]]


{'inf-norm': 31, '1-norm': 35, 'frob-norm': 50.34}

In [ ]:
# Gauss Seidel Iteration
def gauss_seidel(matrix: list(list), b: row):
    
    if not isDiagonallyDominant(matrix):
        return
    
    def function_builder(row: list, b: int, level: int):
        
        if level > len(row):
            return
        
        level_var = row[level]
        other_vars = list(set(row) - set(level_var))
        def output(params):
            for i in row:
                
            func = b - 
        
    # Defining equations to be solved
    # in diagonally dominant form
    f1 = lambda w,x,y,z: (17-y+2*z)/20
    f2 = lambda w,x,y,z: (-18-3*x+z)/20
    f3 = lambda w,x,y,z: (25-2*x+3*y)/20

# Initial setup
x0 = 0
y0 = 0
z0 = 0
count = 1

# Reading tolerable error
e = float(input('Enter tolerable error: '))

# Implementation of Gauss Seidel Iteration
print('\nCount\tx\ty\tz\n')

condition = True

while condition:
    x1 = f1(x0,y0,z0)
    y1 = f2(x1,y0,z0)
    z1 = f3(x1,y1,z0)
    print('%d\t%0.4f\t%0.4f\t%0.4f\n' %(count, x1,y1,z1))
    e1 = abs(x0-x1);
    e2 = abs(y0-y1);
    e3 = abs(z0-z1);
    
    count += 1
    x0 = x1
    y0 = y1
    z0 = z1
    
    condition = e1>e and e2>e and e3>e

print('\nSolution: x=%0.3f, y=%0.3f and z = %0.3f\n'% (x1,y1,z1))